// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlertErro: typeof import('./src/components/alertErro.vue')['default']
    AlertSuccess: typeof import('./src/components/alertSuccess.vue')['default']
    Camp: typeof import('./src/components/camp.vue')['default']
    FormCreateUser: typeof import('./src/components/formCreateUser.vue')['default']
    ListStreet: typeof import('./src/components/listStreet.vue')['default']
    ListUsers: typeof import('./src/components/listUsers.vue')['default']
    Loading: typeof import('./src/components/loading.vue')['default']
    ModalAdd: typeof import('./src/components/modalAdd.vue')['default']
    ModalEdit: typeof import('./src/components/modalEdit.vue')['default']
    ModalEdite: typeof import('./src/components/modalEdite.vue')['default']
    ModalFilter: typeof import('./src/components/modalFilter.vue')['default']
    ModalView: typeof import('./src/components/modalView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
